run:
  deadline: 5m0s

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - vet
    - vetshadow
    - whitespace
    - bodyclose
    - tenv
    - unused
    - asasalint